# Use this file as a starting point for your project's .eslintrc.
# Copy this file, and add rule overrides as needed.
---
extends: airbnb
parser: babel-eslint
rules:
  max-len:
  - error
  - 800
globals:
  DEV: true
  window: true
  document: true
  _: true
  localStorage: true
  lib: true
  describe: true
  it: true
  Component: true
  Toast: true
  React: true
  navigator: true
  PropTypes: true
  moment: true
env:
  es6: true
  browser: true
plugins:
- react
- import
parserOptions:
  ecmaVersion: 7
  sourceType: module
  ecmaFeatures:
    jsx: true
    modules: true
    experimentalObjectRestSpread: true
settings:
  import/resolver:
    webpack:
      config: 'webpack.config.dev.babel.js'
